- name: use role distributed with collection
  hosts: fry       # host we want to run the collection against
  connection: ssh  # default connection type
  gather_facts: no # no need to collect ansible_facts
  become: yes

  # this role is within the collection adalovelace.myfirstcollection
  roles:    
          - adalovelace.myfirstcollection.webservice
            
  tasks:    
          - name: Tasks run after roles
            debug:
                    msg: "Great job! You used a role within the collection adalovelace.myfi
rstcollection"
