---
- name: Copying files from controller to hosts
  hosts: planetexpress

  connection: ssh   # this is a default
  gather_facts: yes # this is a default

  tasks:

    - name: Copy Fry's resume to hosts
      copy:
        src: ~/ans/files/fry.txt   # on the controller
        dest: ~/fry.txt      # home directory on hosts
