---
- name: create unix home directory from storagedetails.yml data in powerscale isilon
  hosts: localhost
  connection: local
  gather_facts: no


  collections:
          - dellemc.isilon

  vars_files:
          - vars/creds.yml
          - vars/storage.yml

  tasks:
          - name: Precheck Operations - Isilon / Powerscale
            block:
                    - name: gather facts on isilon / powerscale
                      dellemc_isilon_gatherfacts:
                              onefs_host: "{{ onefs_host }}"
                              port_no: "{{ isilon_port }}"
                              verify_ssl: "{{ verify_ssl }}"
                              api_user: "{{ api_user }}"
                              api_password: "{{ api_password }}"
                              gather_subset:
                                      - attributes
                      register: results

                    - name: display the results
                      debug:
                              var: results
                              verbosity: 1

                    - name: PRECHECK - Correct number of devices enrolled?
                      fail:
                              msg: "Precheck fail."
                      when: results.Attributes.Config.devices|length != 4

                    - name: PRECHECK - Ensure correct release version running on Cluster
                      fail:
                              msg: "Precheck fail."
                      when: item.release != "v8.2.1.0"
                      loop: "{{ results.Attributes.Cluster_Version.nodes }}"
                      loop_control:
                              label: "{{ item.release }}"

                    - name: PRECHECK - Ensure no current failures on Isilon
                      fail:
                              msg: "Precheck fail."
                      when: results.Attributes.Cluster_Version.errors | length != 0

          - name: Change Operation
            block:
                    - name: CHANGE - Create filesystem with quota for some students
                      dellemc_isilon_filesystem:
                        onefs_host: "{{ onefs_host }}"
                        port_no: "{{ isilon_port }}"
                        verify_ssl: "{{ verify_ssl }}"
                        api_user: "{{ api_user }}"
                        api_password: "{{ api_password }}"
                        path: "{{ base_path }}/students/{{ item }}"
                        owner:
                                name: "root"
                                provider_type: "file"
                        access_control: "{{ access_control }}"
                        recursive: True
                        state: present
                      loop: "{{ students }}"

                    - name: CHANGE - Create filesystem with quota for some teachers
                      dellemc_isilon_filesystem:
                        onefs_host: "{{ onefs_host }}"
                        port_no: "{{ isilon_port }}"
                        verify_ssl: "{{ verify_ssl }}"
                        api_user: "{{ api_user }}"
                        api_password: "{{ api_password }}"
                        path: "{{ base_path }}/teachers/{{ item }}"
                        owner:
                                name: "root"
                                provider_type: "file"
                        access_control: "{{ access_control }}"
                        recursive: True
                        state: present
                      loop: "{{ teachers }}"

                    - name: Force a FAILURE
                      shell:
                              cmd: "/bin/false"

            rescue:
                    - name: RESCUE - start Rollback
                      debug:
                              msg: An error was encountered during the change operation. Attempting Rollback


                    - name: RESCUE - Rollback filesystem with quota for some students
                      dellemc_isilon_filesystem:
                        onefs_host: "{{ onefs_host }}"
                        port_no: "{{ isilon_port }}"
                        verify_ssl: "{{ verify_ssl }}"
                        api_user: "{{ api_user }}"
                        api_password: "{{ api_password }}"
                        path: "{{ base_path }}/students/{{ item }}"
                        owner:
                                name: "root"
                                provider_type: "file"
                        access_control: "{{ access_control }}"
                        recursive: True
                        state: absent
                      loop: "{{ students }}"

                    - name: RESCUE - Rollback filesystem with quota for some teachers
                      dellemc_isilon_filesystem:
                        onefs_host: "{{ onefs_host }}"
                        port_no: "{{ isilon_port }}"
                        verify_ssl: "{{ verify_ssl }}"
                        api_user: "{{ api_user }}"
                        api_password: "{{ api_password }}"
                        path: "{{ base_path }}/teachers/{{ item }}"
                        owner:
                                name: "root"
                                provider_type: "file"
                        access_control: "{{ access_control }}"
                        recursive: True
                        state: absent
                      loop: "{{ teachers }}"

