---
- name: Isilon gather_facts
  hosts: localhost
  connection: local
  gather_facts: no  # we are running in local host mode
                    # we do not want facts about ourselves

  collections:
    - dellemc.isilon

  vars_files:
    - vars/creds.yml

  tasks:
    - name: Gather facts on isilon cluster
      dellemc_isilon_gatherfacts:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ isilon_port }}"
        verify_ssl: "{{ verify_ssl }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        gather_subset:
           - attributes
         # - access_zones
           - nodes
         # - providers
         # - users
         # - groups
      register: results

    - name: display what was just collected
      debug:
        var: results

    - name: copy out results to static file
      copy:
        content: "{{ results.Attributes.Cluster_Version.nodes | to_nice_json }}"
        dest: isilon_facts.json

    - name: Precondition check
      fail:
        msg: "Precondition not met. Wrong number of nodes in the array"
      when: results.Attributes.Cluster_Version.nodes|length != 5
